name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # ðŸ”¥ VERY IMPORTANT

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean conflicting Android env
      run: |
        unset ANDROID_NDK_ROOT
        unset ANDROID_HOME
        unset ANDROID_SDK_ROOT

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openjdk-17-jdk \
        libssl-dev libffi-dev libsqlite3-dev zlib1g-dev unzip wget

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Setup Android SDK cmdline-tools
      run: |
        ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip
        mv cmdline-tools latest

        mkdir -p $ANDROID_HOME/tools/bin
        ln -sf $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
               $ANDROID_HOME/tools/bin/sdkmanager

    - name: Accept Android licenses
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

    - name: Build APK (verbose)
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: StudentLeaveAPK
        path: bin/*.apk
